### PR TITLE
[modes] Allow libproxy use under SDK. JB#59552

### PR DESCRIPTION
**Pull request by martyone**

### CODE REVIEW

**Review by vigejolla — APPROVED** [review]
Somehow one would think that there's a simpler way of accomplishing this. But I guess not.

**Comment by martyone** [comment]
One more call to dbus api was needed to make it actually work and not only silent the original error.

Regarding simpler way, yeah, it's important to not make host's bus visible globally under sb2 session or strange things would happen. Programs can deal with dbus missing, but if dbus is available but the expected service is not, or a service is talked to but the service is actually running on host...

Anyway, only when I debugged it undex i486 target and moved to non-i486 targets, only then I realized this is not going to work for them :( The preload library is used behind qemu in this case, so on much much lower level :facepalm:

**Comment by vigejolla** [comment]
I would have been happy with just suppressing the error ;) But yeah, there is probably someone somewhere who actually needs the functionality.

**Comment by martyone** [comment]
Replaced with https://github.com/sailfishos/pacrunner/pull/2 and https://github.com/sailfishos/sdk-setup/pull/345.

**Pull request closed without merging**
