### PR TITLE
Add config.guess and config.sub automatically if needed

### PR DESCRIPTION
**Pull request by mlehtima**
Needed for new autoconf.

### CODE REVIEW

**Comment by martyone** [comment]
LGTM but https://github.com/sailfishos/scratchbox2/pull/18 needs to be merged or some other fix provided first.

@Thaodan any progress on that front?

**Comment by Thaodan** [comment]
We don't need to add them we can take them from autoconf itself or preffered 
meego-rpm-config (preffered).

**Comment by mlehtima** [comment]
> We don't need to add them we can take them from autoconf itself or preffered meego-rpm-config (preffered).

How? A lot of projects have those in the repos

**Comment by pvuorela** [comment]
Would seem simple enough for me now. Any reason not to merge this?

**Comment by pvuorela** [comment]
Ok, apparently not working good enough yet would be a reason not to merge :)

**Comment by martyone** [comment]
> LGTM but #18 needs to be merged or some other fix provided first.
> 
> @Thaodan any progress on that front?

@Thaodan any conclusion regarding #18? We need to do something about it before this (or any other PR) can be merged.

**Comment by Thaodan** [comment]
> > LGTM but #18 needs to be merged or some other fix provided first.
> > 
> > @Thaodan any progress on that front?
> 
> @Thaodan any conclusion regarding #18? We need to do something about it
> before this (or any other PR) can be merged.
> 
> --
Yes I'll have a fix next week.

**Comment by Thaodan** [comment]
> > We don't need to add them we can take them from autoconf itself or
> > preffered meego-rpm-config (preffered).
> How? A lot of projects have those in the repos
> 

Like you did now or by doing ln -sf from autoconf (I did the latter for my 
Arch package: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?
h=scratchbox2#n26).

Actually our rpm-config should do it do however it is broken right now (need 
to investigate, the commit history is missing before the import, right now it 
looks like we took it from Fedora).

**Comment by pvuorela** [comment]
>Yes I'll have a fix next week.

Week nearing its end. The revert PR is small, thus could perhaps consider just having that first to unblock other development?

**Review by mkosola — APPROVED** [review]

**Pull request merged**
