### PR TITLE
[modes] obs-rpm-build+pp: Fix tools prefix priority more. JB#58627

### PR DESCRIPTION
**Pull request by martyone**

### CODE REVIEW

**Comment by Thaodan** [comment]
To clarify the original change was first 6ccb8bee681edda1d6e032d1146c1a022d4fa809 and then 6ccb8bee681edda1d6e032d1146c1a022d4fa809. The issue is now that tools isn't set from init.lua.

**Comment by Thaodan** [comment]
I think bafdfe9194cd3ed565cd2f415b36df3b27bc9501 should be changed so tools is always set .

**Comment by martyone** [comment]
@Thaodan I don't follow, please explain more what you mean. Unless I missed something `tools` is unconditionally set from `lua_scripts/init.lua`.

**Comment by Thaodan** [comment]
> @Thaodan I don't follow, please explain more what you mean. Unless I missed something `tools` is unconditionally set from `lua_scripts/init.lua`.

It's set to "" when tools_root is "/", which is empty. If ignore that check it should be fine.

**Comment by martyone** [comment]
Hm, maybe I am still missing something? https://github.com/sailfishos/scratchbox2/blob/c9fb642ab6da025140532b1afbf8a1eca630e84c/lua_scripts/init.lua#L77-L85 To me it seems `tools` is set to `tools_root` unless `tools_root` is unset (or empty), in which case `tools` is set to `"/"`. So `tools` is always set and never empty.

**Comment by Thaodan** [comment]
> Hm, maybe I am still missing something?
> 
> https://github.com/sailfishos/scratchbox2/blob/c9fb642ab6da025140532b1afbf8a1eca630e84c/lua_scripts/init.lua#L77-L85
> To me it seems `tools` is set to `tools_root` unless `tools_root` is unset (or empty), in which case `tools` is set to `"/"`. So `tools` is always set and never empty.

Yes you are right but in such as case setting the prefix to tools root would set it to be empty?

**Comment by martyone** [comment]
Do you mean that `tools_prefix` would be empty? That's desired I think. It is used through string concatenation, so when tools are under `"/"`, then `tools_prefix` needs to be empty to avoid double leading slash in paths.

**Review by mkosola — APPROVED** [review]

**Comment by Thaodan** [comment]
> Do you mean that `tools_prefix` would be empty? That's desired I think. It is used through string concatenation, so when tools are under `"/"`, then `tools_prefix` needs to be empty to avoid double leading slash in paths.

I mean that tools should be set to tools_root if tool is empty so has the same content as when you set prefix to tools_root.
Setting prefix to tools_root circumvents in int.lua.

**Comment by martyone** [comment]
I am afraid I still don't follow your concerns. `tools` is the effective path to the tools tree. Tools tree may be either a separate tree (called tooling inside SDK) or the host root is used as the tools root (this is how OBS uses sb2). In the former case `tools_root` is set, in the latter case `tools_root` is empty/unset https://github.com/sailfishos/scratchbox2/blob/c9fb642ab6da025140532b1afbf8a1eca630e84c/utils/sb2-init#L144. While the `tools_root` variable holds the raw value, the `tools` and `tools_prefix` variables are set so that they can be used irrespective of the fact whether a separate tools root is used or not.

**Comment by Thaodan** [comment]
> I am afraid I still don't follow your concerns. `tools` is the effective path to the tools tree. Tools tree may be either a separate tree (called tooling inside SDK) or the host root is used as the tools root (this is how OBS uses sb2). In the former case `tools_root` is set, in the latter case `tools_root` is empty/unset https://github.com/sailfishos/scratchbox2/blob/c9fb642ab6da025140532b1afbf8a1eca630e84c/utils/sb2-init#L144. While the `tools_root` variable holds the raw value, the `tools` and `tools_prefix` variables are set so that they can be used irrespective of the fact whether a separate tools root is used or not.
 
That is what I mean since the obs uses tools_root tools should be set to to tools root  when tools is empty. Now tools is unused and can be removed or used to unify both.
I assumed that the rules above are only for python and Perl while the line you changed is for the rest.

**Comment by martyone** [comment]
> That is what I mean since the obs uses tools_root tools should be set to to tools root  when tools is empty. Now tools is unused and can be removed or used to unify both.

OBS does not use `tools_root`, it uses tools from host filesystem. Grepping for `tools` reveals plenty of uses.

> I assumed that the rules above are only for python and Perl while the line you changed is for the rest.

The rules above do not match - the interpreter is located under build target. The line I changed matched everything, because `tools` is `"/"` on OBS.

**Pull request merged**
